author: PoppyGo
baseURL: / #Hostname (and path) to the root, e.g. https://poppygo.io/
description: ''
#lastmod : [":fileModTime", “:default”]
markup:  #See Configure Markup. New in v0.60.0
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
menu:
  main:
    - identifier: ''
      name: Page Components
      parent: ''
      url: /page-components/
      weight: 3
    - identifier: ''
      name: Posts
      parent: ''
      url: /posts/
      weight: 0
    - identifier: ''
      name: Portfolio
      parent: ''
      url: /portfolio/
      weight: 0
    - identifier: ''
      name: Components ready
      parent: ''
      url: /pages/components-ready/
      weight: 0
params:
  poppygo_debug: true
  poppygo_cms: true
  authorBio: PoppyGo is one year old
  authorbio: ''
  avatar: images/avatar.jpg
  copyright: Copyright © 2021 PoppyGo
  cover: images/vancouver.jpg
  description: 'A minimalist modular theme for Hugo, build with Tailwind'
  email: email@xxxx.com
  github: XXXX
  headline: This is a headline
  linkedin: 'https://linkedin.com/in/XXXX'
  ogImage: images/og_image.jpg
  ogimage: ''
  twitter: XXXX
  umami:
    siteID: XXXXX
    siteid: ''
    trackerScript: //umami.example.com/umami.js
    trackerscript: ''
taxonomies: # See configure taxonomies
  category: categories
  tag: tags
theme: theme-poppygo-one # Theme to use (located by default in /themes/THEMENAME/).
themesDir: themes #(default “themes”) The directory where Hugo reads the themes from.
title: PoppyGo One Hugo Theme # The site title

##Other  settings
archetypeDir:  #(default “archetypes”) The directory where Hugo finds archetype files (content templates). Also see Module Mounts Config for an alternative way to configure this directory (from Hugo 0.56).
assetDir: #(default “assets”) The directory where Hugo finds asset files used in Hugo Pipes. Also see Module Mounts Config for an alternative way to configure this directory (from Hugo 0.56).
blackfriday: #See Configure Blackfriday
build: #See Configure Build
buildDrafts: #(default false) Include drafts when building.
buildExpired: # (default false)Include content already expired.
buildFuture: #(default false) Include content with publishdate in the future.
caches: #See Configure File Caches
canonifyURLs: #(default false) Enable to turn relative URLs into absolute.
contentDir: # default (content) The directory from where Hugo reads content files. Also see Module Mounts Config for an alternative way to configure this directory (from Hugo 0.56).
dataDir: # (default data) The directory from where Hugo reads data files. Also see Module Mounts Config for an alternative way to configure this directory (from Hugo 0.56).
defaultContentLanguage: # (default en) Content without language indicator will default to this language.
defaultContentLanguageInSubdir: #(default false) #Render the default content language in subdir, e.g. content/en/. The site root / will then redirect to /en/.
disableAliases: #(default false) #Will disable generation of alias redirects. Note that even if disableAliases is set, the aliases themselves are preserved on the page. The motivation with this is to be able to generate 301 redirects in an .htaccess, a Netlify _redirects file or similar using a custom output format.
disableHugoGeneratorInject: #(default false) #Hugo will, by default, inject a generator meta tag in the HTML head on the home page only. You can turn it off, but we would really appreciate if you don’t, as this is a good way to watch Hugo’s popularity on the rise.
disableKinds: #[] #Enable disabling of all pages of the specified Kinds. Allowed values in this list: "page", "home", "section", "taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404".
disableLiveReload: # (default false) #Disable automatic live reloading of browser window.
disablePathToLower: # (dafault false) #Do not convert the url/path to lowercase.
enableEmoji: # (default false) Enable Emoji emoticons support for page content; see the Emoji Cheat Sheet.
enableGitInfo:  # (default false) Enable .GitInfo object for each page (if the Hugo site is versioned by Git). This will then update the Lastmod parameter for each page using the last git commit date for that content file.
enableInlineShortcodes:  # (default false) Enable inline shortcode support. See Inline Shortcodes.
enableMissingTranslationPlaceholders: #(default false )Show a placeholder instead of the default value or an empty string if a translation is missing.
enableRobotsTXT:  #(default false) Enable generation of robots.txt file.
frontmatter: #See Front matter Configuration.
footnoteAnchorPrefix: #(default "") Prefix for footnote anchors.
footnoteReturnLinkContents: # ("") Text to display for footnote return links.
googleAnalytics: #(default "")Google Analytics tracking ID.
hasCJKLanguage: #(default false) If true, auto-detect Chinese/Japanese/Korean Languages in the content. This will make .Summary and .WordCount behave correctly for CJK languages.
imaging: #See Image Processing Config.
languages: #See Configure Languages.
languageCode: #(default "")The site’s language code. It is used in the default RSS template and can be useful for multi-lingual sites.
languageName: #(default "") The site’s language name.
disableLanguages: #See Disable a Language
layoutDir: #(default “layouts”) The directory from where Hugo reads layouts (templates).
log:  #(default false) Enable logging.
logFile: #(default "") Log File path (if set, logging enabled automatically).
minify:  #See Configure Minify
module: #Module config see Module Config. New in v0.56.0
newContentEditor: #("") The editor to use when creating new content.
noChmod: #(default false) Don’t sync permission mode of files.
noTimes: #(default false) Don’t sync modification time of files.
paginate: 18 #(default 10) #Default number of elements per page in pagination.
paginatePath: #page (default “page”) The path element used during pagination (https://example.com/page/2).
permalinks: #See Content Management.
pluralizeListTitles: #( default true)Pluralize titles in lists.
publishDir:  #(default “public”) The directory to where Hugo will write the final static site (the HTML files etc.).
related: #See Related Content. New in v0.27
relativeURLs: #(default false) Enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
refLinksErrorLevel: #(default “ERROR”) When using ref or relref to resolve page links and a link cannot resolved, it will be logged with this logg level. Valid values are ERROR (default) or WARNING. Any ERROR will fail the build (exit -1).
refLinksNotFoundURL: #URL to be used as a placeholder when a page reference cannot be found in ref or relref. Is used as-is.
rssLimit: #(default unlimited) Maximum number of items in the RSS feed.
sectionPagesMenu: #("") See “Section Menu for Lazy Bloggers”.
sitemap: #Default sitemap configuration.
staticDir: #default (“static”) A directory or a list of directories from where Hugo reads static files. Also see Module Mounts Config for an alternative way to configure this directory (from Hugo 0.56).
summaryLength: 50 #(default 70) The length of text in words to show in a .Summary.
timeout: # (default 10000) Timeout for generating page contents, in milliseconds (defaults to 10 seconds). Note: this is used to bail out of recursive content generation, if your pages are slow to generate (e.g., because they require large image processing or depend on remote contents) you might need to raise this limit.
titleCaseStyle: #(“AP”)See Configure Title Case
uglyURLs: #(default false) When enabled, creates URL of the form /filename.html instead of /filename/.
verbose: #(default false) Enable verbose output.
verboseLog: #(default false) Enable verbose logging.
watch: # (default false) Watch filesystem for changes and recreate as needed.
