
author: PoppyGo
baseURL: /
hasCJKLanguage: false
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: true
      unsafe: false
      xhtml: false
minify: true
paginate: 18
params:
  authorBio: PoppyGo is one year old
  authorbio: ''
  avatar: images/avatar.jpg
  copyright: Copyright © 2021 PoppyGo
  cover: images/vancouver.jpg
  description: 'A minimalist modular theme for Hugo, build with Tailwind'
  email: email@xxxx.com
  github: XXXX
  headline: This is a headline
  linkedin: 'https://linkedin.com/in/XXXX'
  ogImage: images/og_image.jpg
  ogimage: ''
  poppygo_cms: false
  poppygo_debug: false
  twitter: XXXX
  umami:
    siteID: XXXXX
    siteid: ''
    trackerScript: //umami.example.com/umami.js
    trackerscript: ''
summaryLength: 50
taxonomies:
  category: categories
  tag: tags
theme: theme-poppygo-one
themesDir: themes
title: PoppyGo One Hugo Theme
