author: PoppyGo
baseURL: /
copyright: MIT
description: ''
languageCode: en-us
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Docs
      url: /docs/
      weight: 2
    - name: Content Blocks
      url: /contentblocks/
      weight: 3
params:
  authorBio: 'PoppyGo is one year old'
  authorbio: ''
  avatar: images/avatar.jpg
  copyright: Copyright © 2021 PoppyGo
  cover: images/vancouver.jpg
  description: 'A minimalist modular theme for Hugo, build with Tailwind'
  email: email@xxxx.com
  github: XXXX
  headline: This is a headline
  linkedin: 'https://linkedin.com/in/XXXX'
  ogImage: images/og_image.jpg
  ogimage: ''
  twitter: XXXX
  umami:
    siteID: XXXXX
    siteid: ''
    trackerScript: //umami.example.com/umami.js
    trackerscript: ''
taxonomies:
  category: categories
  tag: tags
theme: poppygo-one
title: PoppyGo One Hugo Theme
