archetypeDir: null
assetDir: null
author: PoppyGo
baseURL: /
blackfriday: null
build: null
buildDrafts: null
buildExpired: null
buildFuture: null
caches: null
canonifyURLs: null
contentDir: null
dataDir: null
defaultContentLanguage: null
defaultContentLanguageInSubdir: null
description: ''
disableAliases: null
disableHugoGeneratorInject: null
disableKinds: null
disableLanguages: null
disableLiveReload: null
disablePathToLower: null
enableEmoji: null
enableGitInfo: null
enableInlineShortcodes: null
enableMissingTranslationPlaceholders: null
enableRobotsTXT: null
footnoteAnchorPrefix: null
footnoteReturnLinkContents: null
frontmatter: null
googleAnalytics: null
hasCJKLanguage: null
imaging: null
languageCode: null
languageName: null
languages: null
layoutDir: null
log: null
logFile: null
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: github
minify: null
module: null
newContentEditor: null
noChmod: null
noTimes: null
paginate: 18
paginatePath: null
params:
  authorBio: PoppyGo is one year old
  authorbio: ''
  avatar: images/avatar.jpg
  copyright: Copyright © 2021 PoppyGo
  cover: images/vancouver.jpg
  description: 'A minimalist modular theme for Hugo, build with Tailwind'
  email: email@xxxx.com
  github: XXXX
  headline: This is a headline
  linkedin: 'https://linkedin.com/in/XXXX'
  ogImage: images/og_image.jpg
  ogimage: ''
  poppygo_cms: false
  poppygo_debug: true
  twitter: XXXX
  pogoselect:
    color:
      - poppycolor1
      - poppycolor2
      - poppycolor3
      - poppycolor4
      - poppycolor5
      - poppycolor6
    bg_color:
      - poppycolor1
      - poppycolor2
      - poppycolor3
      - poppycolor4
      - poppycolor5
      - poppycolor6
    text_color:
      - poppycolor1
      - poppycolor2
      - poppycolor3
      - poppycolor4
      - poppycolor5
      - poppycolor6
    item_bg_color:
      - poppycolor1
      - poppycolor2
      - poppycolor3
      - poppycolor4
      - poppycolor5
      - poppycolor6
    poppy_type:
      - poppy-navigation
      - poppy-footer
      - poppy-banner
      - poppy-shortlist
      - poppy-listing
      - poppy-article
      - poppy-form
    poppy_variant:
      - article1
      - cards1
      - explainer
      - header-banner
      - in-page-banner
      - header-banner-mono
      - gallery1
      - footer
      - navbar
      - navbar-mono
      - 3-column-footer
      - newsletter
      - small-newsletter
      - listcards
      - blog-teaser1
    size:
      - sm
      - md
      - lg
      - xl
      - 2xl
      - 4xl
      - 5xl
      - 6xl
      - 7xl
      - 8xl
      - 9xl
    font:
      - display1
      - display2
      - body
      - art
    shadow:
      - none
      - sm
      - md
      - lg
      - xl
      - 2xl
      - 4xl
      - 5xl
      - 6xl
      - 7xl
      - 8xl
      - 9xl

    list:
      - posts
      - portfolio
      - poppy-components

  umami:
    siteID: XXXXX
    siteid: ''
    trackerScript: //umami.example.com/umami.js
    trackerscript: ''
permalinks: null
pluralizeListTitles: null
publishDir: null
refLinksErrorLevel: null
refLinksNotFoundURL: null
related: null
relativeURLs: null
rssLimit: null
sectionPagesMenu: null
sitemap: null
staticDir: null
summaryLength: 50
taxonomies:
  category: categories
  tag: tags
theme: theme-poppygo-one
themesDir: themes
timeout: null
title: PoppyGo One Hugo Theme
titleCaseStyle: null
uglyURLs: null
verbose: null
verboseLog: null
watch: null
